services:
  arpwatch:
    #image: arpwatch:latest
    build: .
    container_name: arpwatch
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - ./varlib-arpwatch:/var/lib/arpwatch
      - /usr/share/arpwatch:/usr/share/arpwatch:ro
    environment:
      - SMTP_HOST=192.168.1.x
      - ARPWATCH_INTERFACE=br0
      - MAIL_TO=xxxx@xxxx.local
      - MAIL_FROM=root@xxxx.local
      - POSTFIX_MYORIGIN=xxxx.local
      - POSTFIX_MYHOSTNAME=arpwatch.xxxx.local
